# Generated by Django 4.2.1 on 2023-05-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
