# Generated by Django 4.2.1 on 2023-07-14 13:28

import apps.user_profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[apps.user_profile.validators.first_and_last_name_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[apps.user_profile.validators.first_and_last_name_validator]),
        ),
    ]
