# Generated by Django 4.2.1 on 2023-08-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', null=True, upload_to='profile_images'),
        ),
    ]
