# Generated by Django 4.2.1 on 2023-07-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0004_alter_recipe_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.recipe')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ['-published_date'],
            },
        ),
    ]
