# Generated by Django 4.2.1 on 2023-07-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_commentsmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Comment'),
        ),
        migrations.DeleteModel(
            name='LikesModel',
        ),
    ]
