# Generated by Django 4.2.1 on 2023-07-06 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_favoriterecipemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0004_alter_commentsmodel_recipe_alter_commentsmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='recipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
