# Generated by Django 4.2.1 on 2023-07-07 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0006_likesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likesmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='likesmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='user_likes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
