# Generated by Django 4.2.1 on 2023-07-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_likesmodel_user_likesmodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikesModel',
        ),
    ]
