# Generated by Django 4.2.1 on 2023-07-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_commentsmodel_recipe_alter_commentsmodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact forms', 'verbose_name_plural': 'Contact forms'},
        ),
    ]
