# Generated by Django 4.2.1 on 2023-07-14 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
    ]
