# Generated by Django 4.2.1 on 2023-07-14 13:56

import apps.user_profile.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator(message='Invalid email address custom message!!!')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[apps.user_profile.validators.first_and_last_name_validator], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[apps.user_profile.validators.first_and_last_name_validator], verbose_name='Last Name'),
        ),
    ]
