# Generated by Django 4.2.1 on 2023-07-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(error_messages={'required': 'Please, enter a message!'}, verbose_name='Message'),
        ),
    ]
