# Generated by Django 4.2.1 on 2023-07-15 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(error_messages={'required': 'Please, enter a message!'}, validators=[django.core.validators.MinLengthValidator(10, 'Message must be at least 10 characters long!')], verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'Subject must be at least 5 characters long!')], verbose_name='Subject'),
        ),
    ]
