# Generated by Django 4.2.1 on 2023-07-15 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_alter_contact_message_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Please, enter a valid email address!'}, max_length=50, validators=[django.core.validators.EmailValidator], verbose_name='Email'),
        ),
    ]
