# Generated by Django 4.2.1 on 2023-07-15 13:52

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[apps.common.validators.contact_names_validator], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[apps.common.validators.contact_names_validator], verbose_name='Last Name'),
        ),
    ]
