# Generated by Django 4.2.1 on 2023-07-06 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_favoriterecipemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipemodel',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Rating must be equal or greater than 1'), django.core.validators.MaxValueValidator(5, 'Rating must be equal or less than 5')]),
        ),
    ]
