# Generated by Django 4.2.1 on 2023-07-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_favoriterecipemodel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriterecipemodel',
            name='rating',
        ),
    ]
