# Generated by Django 4.2.1 on 2023-07-07 08:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_remove_favoriterecipemodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriterecipemodel',
            name='rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, 'Rating must be equal or greater than 1'), django.core.validators.MaxValueValidator(5, 'Rating must be equal or less than 5')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_recipes', through='recipes.FavoriteRecipeModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
