# Generated by Django 4.2.1 on 2023-07-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_likedrecipe_remove_recipe_likes_delete_like_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedrecipe',
            old_name='post',
            new_name='recipe',
        ),
    ]
