# Generated by Django 4.2.1 on 2023-07-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_rename_post_likedrecipe_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedrecipe',
            options={'verbose_name': 'Likes', 'verbose_name_plural': 'Likes'},
        ),
    ]
