# Generated by Django 4.2.1 on 2023-07-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_likedrecipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipemodel',
            options={'verbose_name': 'Favorite Recipes', 'verbose_name_plural': 'Favorite Recipes'},
        ),
    ]
