# Generated by Django 4.2.1 on 2023-07-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_rename_post_rating_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedrecipe',
            options={'verbose_name': 'Likes', 'verbose_name_plural': 'Recipe Likes'},
        ),
    ]
