# Generated by Django 4.2.1 on 2023-07-14 09:01

import apps.recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_alter_rating_rating_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255, validators=[apps.recipes.validators.recipe_title_validator], verbose_name='Recipe Title'),
        ),
    ]
