# Generated by Django 4.2.1 on 2023-07-17 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_remove_recipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriterecipemodel',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
