# Generated by Django 4.2.1 on 2023-07-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0030_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('salads', 'Salads'), ('soups', 'Soups'), ('main_dishes', 'Main Dishes'), ('bbq', 'BBQ'), ('deserts', 'Desserts')], max_length=11, verbose_name='Recipe Category'),
        ),
    ]
