# Generated by Django 4.2.1 on 2023-08-04 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0035_alter_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mexican', 'Mexican Recipes'), ('italian', 'Italian Recipes'), ('american', 'American Recipes'), ('indian', 'Indian Recipes'), ('french', 'French Recipes'), ('japanese', 'Japanese Recipes'), ('chinese', 'Chinese Recipes'), ('korean', 'Korean Recipes'), ('thai', 'Thai Recipes'), ('spanish', 'Spanish Recipes')], max_length=8, verbose_name='Cuisine')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.cuisine'),
        ),
    ]
