# Generated by Django 4.2.1 on 2023-08-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0036_cuisine_recipe_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='title',
            field=models.CharField(choices=[('Mexican', 'Mexican'), ('Italian', 'Italian'), ('American', 'American'), ('Indian', 'Indian'), ('French', 'French'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese'), ('Korean', 'Korean'), ('Thai', 'Thai'), ('Spanish', 'Spanish'), ('World', 'World')], max_length=50, verbose_name='Cuisine'),
        ),
    ]
