# Generated by Django 4.2.1 on 2023-08-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0040_alter_recipe_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('thai', 'Thai'), ('indian', 'Indian'), ('japanese', 'Japanese'), ('chinese', 'Chinese'), ('korean', 'Korean'), ('italian', 'Italian'), ('spanish', 'Spanish'), ('french', 'French'), ('mexican', 'Mexican'), ('american', 'American'), ('world', 'World')], max_length=8),
        ),
    ]
