# Generated by Django 4.2.1 on 2023-08-07 11:15

import apps.recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0041_alter_recipe_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/', validators=[apps.recipes.validators.file_size_validator], verbose_name='Recipe image'),
        ),
    ]
